baseURL = 'https://ravindradevrani.com/'
languageCode = 'en-us'
title = 'Ravindra Devrani'
theme = 'beautiful-hugo'

[taxonomies]
  category = "categories"
  tag = "tags"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
  
  [[menu.main]]
    identifier = "free-courses"
    name= "Free Courses"
    url = "/free-courses/"
    weight=3 

  [[menu.main]]
    name= "Hands on projects"
    url = "/free-courses/project-tutorials/"
    parent= "free-courses"  
    weight =1

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 5  
[Params] 
  subtitle="I write blog posts and make youtube videos on .NET, C#, SQL and OOA&D"
  readingTime=true
  wordCount=true
  disclaimerText="My views are my own and not my employer's"
  logo= "images/myPic.png"
  favicon = "images/favicon.png"
  favicon16 = "images/favicon-16x16.png"
  favicon32 = "images/favicon-32x32.png"
  apple_touch_icon = "images/apple-touch-icon.png"
  socialShare = true
  socialShareTwitter = true
  socialShareLinkedin = true
  socialShareFacebook = true
  socialShareReddit = true
  socialShareEmail = true
  rss=true
  [Params.author]
    name = "Ravindra Devrani"
    github = "rd003"
    twitter = "ravi_devrani"
    youtube = "@ravindradevrani"
  giscusTheme="preferred_color_scheme"
  disableComments=false
